services:
  mysql:                                            #mysql服务节点
    image: mysql:8.3                              #mysql镜像，如果镜像容器没有会去自动拉取
    container_name: mysql-single                           #容器的名称
    command:                                        #构建容器后所执行的命令
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      # --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower-case-table-names=1    #忽略数据表大小写
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: rootroot
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: mall
      # 初始化用户(不能是root 会报错, 后续需要给新用户赋予权限)
      MYSQL_USER: nacos
      # 用户密码
      MYSQL_PASSWORD: nacos
    ports:
      - 3306:3306
    volumes:
      - mysql-single-data:/data           #数据文件挂载
      - ./conf/my.cnf:/etc/my.cnf    #配置文件挂载
      - mysql-single-log:/var/log/mysql            #日志文件挂载
      - ./init/:/docker-entrypoint-initdb.d/ #数据库初始化脚本文件  只有在 data 下无数据才会初始化

volumes:
  mysql-single-data:
  mysql-single-log:


