version: "3.8"

name: redis-single

services:
  redis-single:
    image: redis:7.2.4
    container_name: redis-single
    restart: always
    environment:
      - TZ=Asia/Shanghai

    volumes:
      - ./etc_rc.local:/etc/rc.local
      - .redis.conf:/etc/redis/redis.conf
      - ./data:/data
      - ./logs/redis-single:/var/redis/log
    ports:
      - 6279:6279
    command: redis-server /etc/redis/redis.conf --port 6279 # 覆盖容器启动后默认执行的命令
