name: redis-single

services:
  redis-single:
    image: redis:7.2.4
    container_name: redis-single
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - redis_data:/data
      - ./logs:/var/redis/log
      - redis_run:/var/run
    ports:
      - 6179:6179
    command: redis-server /etc/redis/redis.conf --port 6179

volumes:
  redis_data:
  redis_logs:
  redis_run: