name: oracle-19c
services:
  oracle_19c:
    # 使用 doctorkirk/oracle-19c 镜像
    image: doctorkirk/oracle-19c
    container_name: oracle-19c
    environment:
      - ORACLE_SID=ORCL
      # 移除了 ORACLE_PDB 和 ORACLE_EDITION，因为原始 docker run 命令中没有这些环境变量
      - ORACLE_PWD=orcl
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=Asia/Shanghai
    # restart: always
    privileged: true
    volumes:
      # 修改为自定义路径的挂载方式
      - oracle_19c_data:/opt/oracle/oradata
      - ./container-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - 1521:1521
      - 5500:5500

volumes:
  oracle_19c_data: