services:
  nginx-ui:
    image: uozi/nginx-ui:v2.0.0-beta.37
    container_name: nginx-ui
    ports:
      - "8002:80"
      - "443:443"
    volumes:
      - ./nginx/nginx:/etc/nginx
      - ./nginx/www:/var/www
      - ./nginx/nginx-ui:/etc/nginx-ui
    environment:
      - TZ=Asia/Shanghai
    tty: true
    stdin_open: true

volumes:
  nginx-config:
  nginx-ui-config:
  nginx-www:

