name: rabbit_mirror
services:
    nginx01:
        container_name: nginx01
        image: nginx
        ports:
          - 82:80
          - 15672:15672
          - 442:443
        volumes:
          - nginx_logs:/var/log/nginx
          # 有可能会出现不能挂载，这个时候用手动拷贝配置文件就行
          - ./nginx.conf/:/etc/nginx/nginx.conf
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - NGINX_PORT=80
          - TZ=Asia/Shanghai
        privileged: true
        depends_on:
          - rabbitmq01
          - rabbitmq02
          - rabbitmq03

    rabbitmq01:
        image: rabbitmq:3.12.14-management-alpine
        container_name: rabbitmq01
        ports:
          - "15673:15672"
          - "5673:5672"
        hostname: rabbitmq01
        environment:
          - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        volumes:
          - rabbitmq_data_1:/var/lib/rabbitmq
          - ./etc/localtime:/etc/localtime

    rabbitmq02:
        image: rabbitmq:3.12.14-management-alpine
        container_name: rabbitmq02
        ports:
          - "15674:15672"
          - "5674:5672"
        hostname: rabbitmq02
        environment:
          - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        volumes:
          - rabbitmq_data_2:/var/lib/rabbitmq
          - ./etc/localtime:/etc/localtime

    rabbitmq03:
        image: rabbitmq:3.12.14-management-alpine
        container_name: rabbitmq03
        ports:
          - "15675:15672"
          - "5675:5672"
        hostname: rabbitmq03
        environment:
          - RABBITMQ_ERLANG_COOKIE=rabbitcookie
        volumes:
          - rabbitmq_data_3:/var/lib/rabbitmq
          - ./etc/localtime:/etc/localtime


volumes:
  rabbitmq_data_1:
  rabbitmq_data_2:
  rabbitmq_data_3:
  nginx_logs: