# save m n，即在m秒内有n次修改时，自动触发bgsave生成rdb文件
save 300 10

# appendonly参数开启AOF持久化
appendonly yes
# aof 缓冲区写入 aof 文件的同步策略
# appendfsync always
appendfsync everysec
# 重写触发配置
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb


# 定义日志级别。
# debug (适用于开发或测试阶段)
# verbose (many rarely useful info, but not a mess like the debug level)
# notice (适用于生产环境)
# warning (仅仅一些重要的消息被记录)
loglevel debug

# 指定日志文件的位置
logfile "log.log"


port 6382
# bind 0.0.0.0
protected-mode no
daemonize no
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 15000
cluster-announce-ip 192.168.0.103
cluster-announce-port 6382
cluster-announce-bus-port 16382