version: '3'
services:
  nginx:
    # restart: always
    container_name: nginx
    image: nginx
    ports:
      - 81:80
      - 442:443
    volumes:
      - nginx_html:/usr/share/nginx/html
      - nginx_www:/var/www
      - nginx_logs:/var/log/nginx
      # 有可能会出现不能挂载，这个时候用手动拷贝配置文件就行
      - ./nginx.conf/:/etc/nginx/nginx.conf
      - ./etc/cert:/etc/nginx/cert
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai
    privileged: true

volumes:
  nginx_logs:
  nginx_www:
  nginx_html: