name: kafka

services:
  kafka1:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1  # Kafka代理的ID
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092  # 广播的监听器地址
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3  # 偏移量主题的复制因子
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_CLUSTER  # 内部代理之间的监听器名称
  kafka2:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka2
    container_name: kafka2
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2  # Kafka代理的ID
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093  # 广播的监听器地址
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3  # 偏移量主题的复制因子
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_CLUSTER  # 内部代理之间的监听器名称
  kafka3:
    image: confluentinc/cp-kafka:6.2.0
    hostname: kafka3
    container_name: kafka3
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3  # Kafka代理的ID
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094  # 广播的监听器地址
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3  # 偏移量主题的复制因子
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_CLUSTER  # 内部代理之间的监听器名称