name: amqp
services:
  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: rabbitmq_3_12
    # 节点名 rabbit@rabbitserver，不然会去容器ID
    hostname: rabbitserver
    environment:
      # 默认虚拟机名
      RABBITMQ_DEFAULT_VHOST: admin_vhost
      # 用户名
      RABBITMQ_DEFAULT_USER: admin
      # 密码
      RABBITMQ_DEFAULT_PASS: admin
      # 指定自定义插件目录
      RABBITMQ_PLUGINS_DIR: '/plugins:/myplugins'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_plugins:/myplugins


volumes:
  rabbitmq_data:
  rabbitmq_plugins: